spring:
  application:
    name: fashion
  thymeleaf:
    prefix: file:src/main/resources/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yamashun?useSSL=false&serverTimezone=UTC
    username: ****
    password: ****
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: myapp.fashion.entity
aws:
  s3:
    bucket-name: fashion-item
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID_FASHIONAPP}
    secret-key: ${AWS_SECRET_ACCESS_KEY_FASHIONAPP}
  region: ap-northeast-1